import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../../services/apiClient";
import { getSocket } from "../../services/socket";
function date(value) { return value ? new Date(value).toLocaleString("es-MX", { dateStyle: "medium", timeStyle: "short" }) : ""; }
function text(item) { const actor = item.actor?.displayName || item.actor?.username || "Alguien"; return item.type === "follow" ? `${actor} comenzó a seguirte.` : item.type === "like" ? `${actor} indicó que le gusta tu publicación.` : item.type === "comment" ? `${actor} comentó tu publicación.` : `${actor} generó actividad en Kronos.`; }
export default function Notifications() { const [items, setItems] = useState([]); const [unread, setUnread] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); async function load() { setLoading(true); setError(""); try { const { data } = await api.get("/notifications"); setItems(Array.isArray(data?.notifications) ? data.notifications : []); setUnread(Number(data?.unreadCount || 0)); } catch (requestError) { setError(requestError.response?.data?.error || "No se pudieron cargar las notificaciones."); } finally { setLoading(false); } } useEffect(() => { load(); }, []); useEffect(() => { const socket = getSocket(); if (!socket) return undefined; const receive = item => { if (!item?._id) return; setItems(current => current.some(existing => existing._id === item._id) ? current : [item, ...current]); setUnread(value => value + 1); }; socket.on("notification:new", receive); return () => socket.off("notification:new", receive); }, []); async function mark(id) { try { await api.patch(`/notifications/${id}/read`); setItems(current => current.map(item => item._id === id ? { ...item, read: true } : item)); setUnread(value => Math.max(0, value - 1)); } catch { setError("No se pudo marcar la notificación."); } } async function markAll() { if (!unread) return; try { await api.patch("/notifications/read-all"); setItems(current => current.map(item => ({ ...item, read: true }))); setUnread(0); } catch (requestError) { setError(requestError.response?.data?.error || "No se pudieron marcar todas."); } }
  if (loading) return <section className="page"><div className="k-feed-state"><span className="k-skeleton" /><span className="k-skeleton k-skeleton-wide" /></div></section>;
  return <section className="page"><header className="k-page-header"><div><p className="k-eyebrow">KRONOS / ACTIVITY</p><h1>Notificaciones</h1><p>{unread ? `${unread} sin leer` : "Todo al día"}</p></div><button className="k-button k-button-secondary" type="button" onClick={markAll} disabled={!unread}>Marcar todas como leídas</button></header>{error && <p className="k-state k-state-error" role="alert">{error}</p>}{items.length === 0 ? <div className="k-empty-state"><h2>No tienes notificaciones</h2><p>La actividad de tu comunidad aparecerá aquí.</p></div> : <div className="k-notification-list">{items.map(item => { const destination = item.post ? `/post/${item.post._id}` : item.actor?._id ? `/users/${item.actor._id}` : "/notifications"; return <article className={`k-surface k-notification ${item.read ? "is-read" : "is-unread"}`} key={item._id}><Link to={destination} onClick={() => !item.read && mark(item._id)}><strong>{text(item)}</strong><small>{date(item.createdAt)}</small></Link></article>; })}</div>}</section>;
}
