import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api } from "../../services/apiClient";
import { getUser } from "../../services/authStorage";
import { getSocket } from "../../services/socket";
function date(value) { return value ? new Date(value).toLocaleString("es-MX", { dateStyle: "medium", timeStyle: "short" }) : ""; }
function ids(value) { return String(value?._id || value || ""); }
export default function Messages() { const { userId } = useParams(); const currentUserId = String(getUser()?._id || getUser()?.id || ""); const [messages, setMessages] = useState([]); const [conversations, setConversations] = useState([]); const [content, setContent] = useState(""); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [error, setError] = useState(""); const [connected, setConnected] = useState(true);
  async function load() { setLoading(true); setError(""); try { if (userId) { const { data } = await api.get(`/messages/${userId}`); setMessages(Array.isArray(data?.messages) ? data.messages : []); await api.patch(`/messages/${userId}/read`); } else { const { data } = await api.get("/messages"); setConversations(Array.isArray(data?.conversations) ? data.conversations : []); } } catch (requestError) { setError(requestError.response?.data?.error || "No se pudieron cargar los mensajes."); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [userId]);
  useEffect(() => { const socket = getSocket(); if (!socket || !userId) return undefined; const online = () => setConnected(true); const offline = () => setConnected(false); const receive = message => { const sender = ids(message.sender); const receiver = ids(message.receiver); if ((sender === currentUserId && receiver === String(userId)) || (receiver === currentUserId && sender === String(userId))) setMessages(items => items.some(item => item._id === message._id) ? items : [...items, message]); }; socket.on("connect", online); socket.on("disconnect", offline); socket.on("message:new", receive); return () => { socket.off("connect", online); socket.off("disconnect", offline); socket.off("message:new", receive); }; }, [currentUserId, userId]);
  async function send(event) { event.preventDefault(); const text = content.trim(); if (!text || sending || !userId) return; setSending(true); setError(""); try { const { data } = await api.post(`/messages/${userId}`, { text }); if (data?.message) setMessages(items => [...items, data.message]); setContent(""); } catch (requestError) { setError(requestError.response?.data?.error || "No se pudo enviar el mensaje."); } finally { setSending(false); } }
  const other = useMemo(() => { const item = messages.find(message => ids(message.sender) !== currentUserId || ids(message.receiver) !== currentUserId); if (!item) return null; return ids(item.sender) === currentUserId ? item.receiver : item.sender; }, [messages, currentUserId]);
  if (loading) return <section className="page"><div className="k-feed-state"><span className="k-skeleton" /><span className="k-skeleton k-skeleton-wide" /></div></section>;
  if (!userId) return <section className="page"><header className="k-page-header"><div><p className="k-eyebrow">KRONOS / MESSAGES</p><h1>Mensajes</h1><p>Conversaciones recientes.</p></div></header>{error && <p className="k-state k-state-error" role="alert">{error}</p>}{conversations.length === 0 ? <div className="k-empty-state"><h2>No tienes conversaciones</h2><p>Abre un perfil para iniciar un chat.</p></div> : <div className="k-conversation-list">{conversations.map(item => <Link className="k-surface k-conversation" key={item.user?._id} to={`/messages/${item.user?._id}`}><strong>{item.user?.displayName || item.user?.username || "Usuario"}</strong><span>{item.latestMessage?.text}</span><small>{date(item.latestMessage?.createdAt)}{item.unreadCount ? ` · ${item.unreadCount} sin leer` : ""}</small></Link>)}</div>}</section>;
  return <section className="page"><header className="k-page-header"><div><p className="k-eyebrow">KRONOS / CHAT {connected ? "· EN LÍNEA" : "· RECONECTANDO"}</p><h1>{other?.displayName || other?.username || "Conversación"}</h1><p>@{other?.username || userId}</p></div><Link className="k-button k-button-ghost" to="/messages">Volver</Link></header>{error && <p className="k-state k-state-error" role="alert">{error}</p>}<div className="k-message-list" aria-live="polite">{messages.length === 0 ? <div className="k-empty-state"><h2>Aún no hay mensajes</h2><p>Escribe el primero.</p></div> : messages.map(message => <article className={`k-message ${ids(message.sender) === currentUserId ? "is-own" : ""}`} key={message._id}><p>{message.text}</p><small>{date(message.createdAt)}</small></article>)}</div><form className="k-message-composer" onSubmit={send}><textarea value={content} onChange={event => setContent(event.target.value)} maxLength={5000} placeholder="Escribe un mensaje..." aria-label="Escribir mensaje" disabled={sending} /><button className="k-button k-button-primary" type="submit" disabled={sending || !content.trim()}>{sending ? "Enviando..." : "Enviar"}</button></form></section>;
}
